import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { Analytics } from '@vercel/analytics/next';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/images/adib.png" type="image/gif" />
        {/* Or use SVG */}
        {/* <link rel="icon" href="/favicon.svg" type="image/svg+xml" /> */}
      </Head>
      <body className={inter.className}>{children}</body>
      <Analytics />
    </html>
  )
}
